# Run locally:
#    docker compose -f docker-compose.yml -f docker-compose.local.yml  up -d

services:
  db:
    env_file: ../.env

  api:
    env_file: ../.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - 9081:8001 # acccess on localhost 9081

  event-worker:
    env_file: ../.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      WAIT_HOSTS: db:5432, api:8001

  webhook-executor:
    env_file: ../.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      WAIT_HOSTS: db:5432, api:8001
